name: herenow_backend
description: Alfred server project for project 'HereNow'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  alfred: ^1.1.1
  mime: ^1.0.5
  path: ^1.9.0
  sqlite3: ^2.4.4
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
