name: herenow_backend
description: Alfred server project for project 'HereNow'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  alfred: ^1.1.1
  mime: ^1.0.5
  path: ^1.9.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.24
  #postgres: ^3.2.1
  dotenv: ^4.2.0
  http: ^1.2.1
  #aws_s3_api: ^2.0.0
  #flutter_aws_s3_client: ^0.6.0
  #amplify_flutter: ^2.2.0
  #amplify_storage_s3: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
